//Auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//Errors
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//Turfs
export const GET_TURFS = 'GET_TURFS';
export const TURFS_LOADING = 'TURFS_LOADING';
export const GET_TURFS_ERROR = 'GET_TURFS_ERROR';
export const SELECT_TURF = 'SELECT_TURF';

//Business Turfs
export const GET_BUSINESS_TURFS = 'GET_BUSINESS_TURFS';
export const BUSINESS_TURFS_LOADING = 'BUSINESS_TURFS_LOADING';
export const GET_BUSINESS_TURFS_ERROR = 'GET_BUSINESS_TURFS_ERROR';